# Generated by Django 3.2.6 on 2021-09-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
