# Generated by Django 3.2.6 on 2021-09-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
